# Generated by Django 5.2.11 on 2026-02-18 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawBlogsEntries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_image_url', models.TextField()),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('info_subtitles', models.TextField()),
                ('info_data', models.TextField()),
            ],
        ),
    ]
