# Generated by Django 5.2.11 on 2026-02-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawblogsentries',
            name='info_subtitles',
            field=models.JSONField(),
        ),
    ]
