# Generated by Django 5.2.11 on 2026-02-21 00:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rawblogsentries_info_subtitles'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogProcessedEntries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
    ]
